openapi: 3.0.0
x-stoplight:
  id: w8df3r00wgbkc
info:
  title: koder-open-api
  version: '1.0'
servers: []
paths:
  /users:
    get:
      summary: Get Users list
      tags:
        - user
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/User'
                required:
                  - items
              examples:
                android:
                  value:
                    items:
                      - id: 497f6eca-6276-4993-bfeb-53qweca
                        avatarUrl: 'https://api.lorem.space/image/face?w=120&h=120'
                        firstName: John
                        lastName: Doe
                        userTag: jd
                        department: android
                        position: developer
                        birthday: '1973-01-24'
                        phone: '+79001234567'
                ios:
                  value:
                    items:
                      - id: 497f6eca-6276-4993-bfeb-53gasfaf08
                        avatarUrl: 'https://api.lorem.space/image/face?w=120&h=120'
                        firstName: Mike
                        lastName: Smith
                        userTag: ms
                        department: ios
                        position: IOS developer
                        birthday: '1992-04-14'
                        phone: '+79001234512'
                design:
                  value:
                    items:
                      - id: 497f6eca-6276-4993-bfeb-53cbbbb6fhd
                        avatarUrl: 'https://api.lorem.space/image/face?w=120&h=120'
                        firstName: Jany
                        lastName: Brown
                        userTag: jb
                        department: design
                        position: developer
                        birthday: '2001-09-01'
                        phone: '+79001234513'
                management:
                  value:
                    items:
                      - id: 497f6eca-6276-4993-bfeb-53cvfhAs
                        avatarUrl: 'https://api.lorem.space/image/face?w=120&h=120'
                        firstName: Boby
                        lastName: Jones
                        userTag: bj
                        department: management
                        position: project manager
                        birthday: '1993-08-24'
                        phone: '+79001234514'
                qa:
                  value:
                    items:
                      - id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
                        avatarUrl: 'https://api.lorem.space/image/face?w=120&h=120'
                        firstName: Michael
                        lastName: Scott
                        userTag: ms
                        department: qa
                        position: Team Lead
                        birthday: '1983-08-05'
                        phone: '+79001234515'
                back_office:
                  value:
                    items:
                      - id: 497f6eca-6276-4993-bfeb-53cbbbba6hjycaejh08
                        avatarUrl: 'https://api.lorem.space/image/face?w=120&h=120'
                        firstName: David
                        lastName: Garcia
                        userTag: dg
                        department: back_office
                        position: Office manager
                        birthday: '1990-01-22'
                        phone: '+79001234516'
                frontend:
                  value:
                    items:
                      - id: 497f6eca-6276-4993-bfeb-53cbbbba6re3
                        avatarUrl: 'https://api.lorem.space/image/face?w=120&h=120'
                        firstName: Dan
                        lastName: Miller
                        userTag: dm
                        department: frontend
                        position: developer
                        birthday: '1990-01-21'
                        phone: '+79001234517'
                hr:
                  value:
                    items:
                      - id: 497f6eca-6276-4993-bfeb-53cbbbbssaga6f08
                        avatarUrl: 'https://api.lorem.space/image/face?w=120&h=120'
                        firstName: Richard
                        lastName: Davis
                        userTag: string
                        department: hr
                        position: Team Lead
                        birthday: '2003-01-24'
                        phone: '+79001234518'
                pr:
                  value:
                    items:
                      - id: 497f6eca-6276-4993-bfeb-53cbbbba35gs76f08
                        avatarUrl: 'https://api.lorem.space/image/face?w=120&h=120'
                        firstName: Joseph
                        lastName: Martinez
                        userTag: jm
                        department: pr
                        position: writer
                        birthday: '2003-01-01'
                        phone: '+79001234519'
                backend:
                  value:
                    items:
                      - id: 497f6eca-6276-4993-bfeb-fjxffgsy4
                        avatarUrl: 'https://api.lorem.space/image/face?w=120&h=120'
                        firstName: Thomas
                        lastName: Lopez
                        userTag: Tech Lead
                        department: backend
                        position: string
                        birthday: '2019-08-24'
                        phone: '+79001234520'
                support:
                  value:
                    items:
                      - id: 497f6eca-6276-4993-bfeb-sdg6qdgyj
                        avatarUrl: 'https://api.lorem.space/image/face?w=120&h=120'
                        firstName: Charles
                        lastName: Thomas
                        userTag: string
                        department: support
                        position: support manager
                        birthday: '2019-08-24'
                        phone: '+79001234521'
                analytics:
                  value:
                    items:
                      - id: 497f6eca-6276-4993-bfeb-dddw4yuk3
                        avatarUrl: 'https://api.lorem.space/image/face?w=120&h=120'
                        firstName: Christopher
                        lastName: Taylor
                        userTag: ct
                        department: analytics
                        position: Team Lead
                        birthday: '2019-08-24'
                        phone: '+79001234522'
                all:
                  value:
                    items:
                      - id: 497f6eca-6276-4993-bfeb-53qweca
                        avatarUrl: 'https://api.lorem.space/image/face?w=120&h=120'
                        firstName: John
                        lastName: Doe
                        userTag: jd
                        department: android
                        position: developer
                        birthday: '1973-01-24'
                        phone: '+79001234567'
                      - id: 497f6eca-6276-4993-bfeb-53gasfaf08
                        avatarUrl: 'https://api.lorem.space/image/face?w=120&h=120'
                        firstName: Mike
                        lastName: Smith
                        userTag: ms
                        department: ios
                        position: IOS developer
                        birthday: '1992-04-14'
                        phone: '+79001234512'
                      - id: 497f6eca-6276-4993-bfeb-53cbbbb6fhd
                        avatarUrl: 'https://api.lorem.space/image/face?w=120&h=120'
                        firstName: Jany
                        lastName: Brown
                        userTag: jb
                        department: design
                        position: developer
                        birthday: '2001-09-01'
                        phone: '+79001234513'
                      - id: 497f6eca-6276-4993-bfeb-53cvfhAs
                        avatarUrl: 'https://api.lorem.space/image/face?w=120&h=120'
                        firstName: Boby
                        lastName: Jones
                        userTag: bj
                        department: management
                        position: project manager
                        birthday: '1993-08-24'
                        phone: '+79001234514'
                      - id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
                        avatarUrl: 'https://api.lorem.space/image/face?w=120&h=120'
                        firstName: Michael
                        lastName: Scott
                        userTag: ms
                        department: qa
                        position: Team Lead
                        birthday: '1983-08-05'
                        phone: '+79001234515'
                      - id: 497f6eca-6276-4993-bfeb-53cbbbba6hjycaejh08
                        avatarUrl: 'https://api.lorem.space/image/face?w=120&h=120'
                        firstName: David
                        lastName: Garcia
                        userTag: dg
                        department: back_office
                        position: Office manager
                        birthday: '1990-01-22'
                        phone: '+79001234516'
                      - id: 497f6eca-6276-4993-bfeb-53cbbbba6re3
                        avatarUrl: 'https://api.lorem.space/image/face?w=120&h=120'
                        firstName: Dan
                        lastName: Miller
                        userTag: dm
                        department: frontend
                        position: developer
                        birthday: '1990-01-21'
                        phone: '+79001234517'
                      - id: 497f6eca-6276-4993-bfeb-53cbbbbssaga6f08
                        avatarUrl: 'https://api.lorem.space/image/face?w=120&h=120'
                        firstName: Richard
                        lastName: Davis
                        userTag: string
                        department: hr
                        position: Team Lead
                        birthday: '2003-01-24'
                        phone: '+79001234518'
                      - id: 497f6eca-6276-4993-bfeb-53cbbbba35gs76f08
                        avatarUrl: 'https://api.lorem.space/image/face?w=120&h=120'
                        firstName: Joseph
                        lastName: Martinez
                        userTag: jm
                        department: pr
                        position: writer
                        birthday: '2003-01-01'
                        phone: '+79001234519'
                      - id: 497f6eca-6276-4993-bfeb-fjxffgsy4
                        avatarUrl: 'https://api.lorem.space/image/face?w=120&h=120'
                        firstName: Thomas
                        lastName: Lopez
                        userTag: Tech Lead
                        department: backend
                        position: string
                        birthday: '2019-08-24'
                        phone: '+79001234520'
                      - id: 497f6eca-6276-4993-bfeb-sdg6qdgyj
                        avatarUrl: 'https://api.lorem.space/image/face?w=120&h=120'
                        firstName: Charles
                        lastName: Thomas
                        userTag: string
                        department: support
                        position: support manager
                        birthday: '2019-08-24'
                        phone: '+79001234521'
                      - id: 497f6eca-6276-4993-bfeb-dddw4yuk3
                        avatarUrl: 'https://api.lorem.space/image/face?w=120&h=120'
                        firstName: Christopher
                        lastName: Taylor
                        userTag: ct
                        department: analytics
                        position: Team Lead
                        birthday: '2019-11-24'
                        phone: '+79001234522'
            application/xml:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/User'
        '500':
          description: Internal Server Error
      operationId: get-users
      description: Get Users list
      parameters:
        - schema:
            type: string
          in: query
          name: __example
          description: Параметр фильтрации пользователей по полю "department"
        - schema:
            type: string
            enum:
              - '500'
          in: query
          name: __code
          description: Эмуляция кода ответа сервера
        - schema:
            type: boolean
          in: query
          name: __dynamic
          description: Тип моковых данных. True - динамически генерируемые данные (рекомендуется использовать для проверки UI на устойчивость к разным данным)
    parameters: []
components:
  schemas:
    User:
      type: object
      x-examples: {}
      title: User
      properties:
        id:
          type: string
          x-faker: datatype.uuid
        avatarUrl:
          type: string
          x-faker: image.avatar
          example: 'https://picsum.photos/120/120'
          default: 'https://picsum.photos/120/120'
        firstName:
          type: string
          x-faker: name.firstName
          minLength: 3
          maxLength: 6
          example: John
        lastName:
          type: string
          x-faker: name.lastName
          example: Doe
        userTag:
          type: string
          x-faker: address.countryCode
        department:
          type: string
          enum:
            - android
            - ios
            - design
            - management
            - qa
            - back_office
            - frontend
            - hr
            - pr
            - backend
            - support
            - analytics
        position:
          x-faker: name.jobType
          type: string
        birthday:
          type: string
          format: date
        phone:
          type: string
          x-faker: phone.phoneNumberFormat
          example: '+79001234567'
      required:
        - id
        - avatarUrl
        - firstName
        - lastName
        - userTag
        - department
        - position
        - birthday
        - phone
